sources:
  - name: src
    database: SOURCEDB
    schema: MK_MALL
    tables:
      - name: customers
      - name: v_nations
      - name: regions
      - name: nations
        columns:
        - name: nation_id
          data_type: int
          constraints:
            - type: not_null
        - name: nation_name
          data_type: string
          constraints:
            - type: not_null

          description: '{{doc("primary_key")}}'
          data_tests:
            - not_null
            - unique
        - name: region_id
          data_type: int
          data_tests:
            - relationships:
                to: ref('stg_regions')
                field: region_id
                config:
                  store_failures: true
      - name: suppliers
      - name: partsupps
      - name: orders
        config:
          freshness:
            warn_after: {count: 3, period: day}
            error_after: {count: 5, period: day}
          meta:
            loaded _at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name: parts
  - name: src2
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees