sources:
  - name: src
    database: SOURCEDB
    schema: MK_MALL
    tables:
      - name: customers
      - name: v_nations
      - name: regions
      - name: nations
      - name: suppliers
      - name: partsupps
      - name: orders
        config:
          freshness:
            warn_after: {count: 1, period: hour}
            error_after: {count: 5, period: hour}
          loaded _at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name: parts
  - name: src2
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees
      